BaSD-MS-121: Refactor applications resource
BaSD-2021/Esteban-MindSet-app pull request #46
Opened 2021-12-19 22:07 UTC by veronabaudracco

- [X] Adapt the Applications screen filtering by the chosen postulant

2021-12-23 01:59 UTC, fjmorabito requested changes

2021-12-23 01:59 UTC, fjmorabito commented on src/Components/Postulant/Applications/index.js
> +            onRowClick={(item) => history.push(`/admin/applications/form?_id=${item._id}`)}
On row click redirecting somewhere it shouldn´t.

2021-12-23 17:30 UTC, AgustinCarthery approved these changes

2021-12-27 23:35 UTC, fjmorabito approved these changes

2021-12-27 23:37 UTC, merged