BaSD-MS-129: refactor profile position and session
BaSD-2021/Esteban-MindSet-app pull request #51
Opened 2021-12-20 03:09 UTC by fjmorabito

In this feature profile, position and session are refactored using React Final Form.

- Add validations on form fields.
- Implement React Final Form
- Add new shared components to mantain integrity between the screens.

2021-12-22 15:31 UTC, veronabaudracco requested changes

2021-12-22 15:31 UTC, veronabaudracco commented on src/Components/Admin/Positions/Form/index.js
> +  const validate = (formValues) => {
You should add a validation in the vacancy field so that it supports only integers

2021-12-23 15:42 UTC, veronabaudracco approved these changes

2021-12-27 23:35 UTC, estefrare approved these changes

2021-12-27 23:36 UTC, merged