[WIP] BASD-MS-119/Dashboard view
BaSD-2021/Esteban-MindSet-app pull request #53
Opened 2021-12-21 02:40 UTC by AgustinCarthery

2021-12-22 16:03 UTC, veronabaudracco requested changes
-Postulant should be allowed to cancel or reschedule the session from the dashboard
-Postulant should be allowed to cancel schedule interviews from the dashboard

2021-12-25 18:52 UTC, AgustinCarthery commented
> -Postulant should be allowed to cancel or reschedule the session from the dashboard -Postulant should be allowed to cancel schedule interviews from the dashboard

Fixed, wasn't aware of A/C for the issue, thanks

2021-12-27 23:50 UTC, veronabaudracco approved these changes

2021-12-27 23:50 UTC, estefrare approved these changes

2021-12-27 23:53 UTC, merged