BaSD-MS-128: react final form psychologist client
BaSD-2021/Esteban-MindSet-app pull request #57
Opened 2021-12-22 03:12 UTC by fjmorabito

IIn this feature client and psychologist are being implement React Final Form.

- Add validations on form fields
- Implement React Final Form
- Add new shared components to mantain integrity between the screens.
- Add route to psychologist form

2021-12-22 15:46 UTC, veronabaudracco requested changes

2021-12-22 15:46 UTC, veronabaudracco commented on src/Components/Admin/Clients/Form/index.js
> +  const validate = (formValues) => {
You should add a validation so that the inputs name and state admit only letters

2021-12-22 15:55 UTC, veronabaudracco requested changes

2021-12-22 15:55 UTC, veronabaudracco commented on src/Components/Admin/Clients/Form/index.js
> +    if (formValues.name?.search(/[0-9]/) > 0) {
This validation doesn't work

2021-12-27 23:50 UTC, veronabaudracco approved these changes

2021-12-27 23:50 UTC, estefrare approved these changes

2021-12-27 23:58 UTC, merged