BaSD-MS-64: add Interviews entity form and list table
BaSD-2021/Esteban-MindSet-app pull request #6
Opened 2021-11-29 22:46 UTC by veronabaudracco

Client entity:
Added components to show all Interview entities on a table, modal and form to edit and create a new one.

Valid functionalities:

- [x] CreateCreate
- [x] Visualize
- [x] Remove
- [x] Edit

2021-11-30 17:04 UTC, AgustinCarthery commented on src/Components/Interviews/Form/form.module.css
> +select, input{
avoid tag name selectors

2021-11-30 17:04 UTC, AgustinCarthery commented on src/Components/Interviews/Form/index.js
> +                {postulant.firstName + ' ' + postulant.lastName}
literal string would suit better

2021-11-30 20:01 UTC, estefrare requested changes

2021-11-30 20:01 UTC, estefrare commented on package.json
> +    "react-scripts": "^4.0.3",
do not update this library

2021-11-30 20:01 UTC, estefrare commented on src/Components/Interviews/Form/index.js
> +      .then((res) => {
remove this `.then`

2021-11-30 20:01 UTC, estefrare commented on src/Components/Interviews/Form/index.js
> +        console.log('err', error);
show errors in the UI

2021-11-30 20:01 UTC, estefrare commented on src/Components/Interviews/Form/index.js
> +        console.log('err', error);
show errors in the UI, apply this on each `.catch()`

2021-11-30 20:01 UTC, estefrare commented on src/Components/Interviews/Form/index.js
> +          </option>
```suggestion
          <option value={''} disabled>
            Select one
          </option>
```

2021-12-02 15:58 UTC, estefrare approved these changes

2021-12-02 16:08 UTC, AgustinCarthery approved these changes

2021-12-02 16:18 UTC, merged