BaSD-MS-66: add Positions entity form and list table
BaSD-2021/Esteban-MindSet-app pull request #8
Opened 2021-11-30 01:10 UTC by veronabaudracco

Client entity:
Added components to show all Interview entities on a table, modal and form to edit and create a new one.

Valid functionalities:

- [x]  CreateCreate
- [x]  Visualize
- [x]  Remove
- [x]  Edit

2021-11-30 16:57 UTC, AgustinCarthery commented on src/Components/Positions/Form/form.module.css
> +select, input{
use class selector instead of tag name

2021-11-30 16:57 UTC, AgustinCarthery commented on src/Components/Positions/Form/index.js
> +      .then((res) => {
'd rather remove the console.log

2021-11-30 19:49 UTC, estefrare requested changes

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/form.module.css
> +button {
do not use pure tags

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/list.module.css
> +tbody tr{
do not use pure tags

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/index.js
> +        console.log('err', error);
show the errors in the UI otherwise the user never will see what happens

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/index.js
> +          console.log('err', error);
show the errors in the UI otherwise the user never will see what happens

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +          </option>
```suggestion
          <option value={''} disabled>
            Select one
          </option>
```

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +          </option>
```suggestion
          <option value={''} disabled>
            Select one
          </option>
```

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +          console.log('err', error);
show the error in the UI

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +        console.log('err', error);
show the error in the UI

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +        console.log('err', error);
show the error in the UI

2021-11-30 19:49 UTC, estefrare commented on src/Components/Positions/Form/index.js
> +        console.log('err', error);
show the error in the UI

2021-12-02 16:32 UTC, estefrare approved these changes

2021-12-02 16:34 UTC, AgustinCarthery approved these changes

2021-12-02 16:34 UTC, merged